general:
  path: ./
  prefix: v772Cas
  iter: i01
  primary_obs: data/v772Cas_primary_RVs.dat
  secondary_obs: None
  chains: 2
  cores: 4
  draws: 1000
  tune: 1000
  target: 0.97
  type: rv
  ecc_type: small
varpars:
  Period:
    prior: Uniform
    transform: log
    kwargs:
      testval: 5.01370
      lower: 4.8
      upper: 5.2
  Gamma:
    prior: Uniform
    transform: None
    kwargs:
      testval: 0.
      lower: -100.
      upper: 100.
  K1:
    prior: Uniform
    transform: log
    kwargs:
      testval: 60.5
      lower: 1.
      upper: 400
priors:
  ecc:
    mean: 0.
    std: 0.4
  omega:
    mean: 3.14
    std: 0.1
